### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by AgoraSecurity** [Jekyll-Bootstrap/jekyll-bs5#4]
https://yosileyid.github.io/jekyll-bootstrap-starter/ gives a 404

**Comment by yosileyid** [comment]
My bad! I moved them to the "jekyll-bootstrap org. I need to update readmes
but I'm working on a lot. You can go to
https://jekyll-bootstrap.github.io/jekyll-bs5 it has a couple layout issues
but it works on that link. Thank you for bringing it to my attention.

**Comment by AgoraSecurity** [comment]
Thank you for the super quick answer :)
